// <auto-generated />
namespace FaceBookApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatecomment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecomment));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180345136_update comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
